### ISSUE TITLE
大bug

### ISSUE THREAD

**Issue by lswen** [tavenli/port-forward#3]
差个库， forward-core/common   搞事情...

**Comment by tavenli** [comment]
周末赶着刚弄完的新功能，整个工程结构都改了，只是没来得及提交而已，就有意见了？

**Comment by tavenli** [comment]
看到这样一个 倒过来的 大拇指，有时候真是心里凉凉的

**Comment by tavenli** [comment]
开源的目的是相互交流和学习，让有能力的人，一起来贡献代码，但是并不是义务。我也是每天白天要忙公司的项目，晚上放弃娱乐休息时间，抽出时间写点这个，就有点家里的事情，耽误了一两天，没提交代码而已，至于这样吗？你哪怕是问一下 "forward-core/common' 为什么没有提交，什么时候能提交上来，我心里都舒服很多。

**Comment by lswen** [comment]
哈哈， 多心了，。。。
