### ISSUE TITLE
好神奇的bug.... 研究很久实在是没法解决了&汇报一个bug

### ISSUE THREAD

**Issue by cytvictor** [tavenli/port-forward#5]

**Comment by cytvictor** [comment]
补充：在第一次报错之后，重启port-forward后请求相同的Api内容时，可以成功开启转发，不知道这能不能让您排查得更细 :blush:

例如，第一次请求 
![image](https://user-images.githubusercontent.com/13085122/37728246-b6d38dfc-2d74-11e8-8504-e5c0ee429e2f.png)
第二次请求就可以 
![image](https://user-images.githubusercontent.com/13085122/37728257-bd5bb384-2d74-11e8-9b55-f577e25e8c26.png)

**Comment by jinjin123** [comment]
@cytvictor  socket 通道复用出现问题

**Comment by cytvictor** [comment]
> @cytvictor socket 通道复用出现问题

Thanks for your help:)

**Comment by caoshitong369** [comment]
![image](https://user-images.githubusercontent.com/44139321/184300066-b56897a9-5ed5-4fe9-9693-905d14a9170c.png)
重新给entriy赋值
